spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/teamwork
    url: jdbc:mysql://47.96.236.167:3306/fzucommunity
    password: 123456
    username: team3
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

mvc:
  hiddenmethod:
    filter:
      enabled: true

config:
  jwt:
    # 加密密钥
    secret: abcdefg1234567
    # token有效时长
    expire: 3600
    # header 名称
    header: token
